# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3529750375b1ae3227004e4aaaf0060901efed09aea4d04574f9e986dab14e16dc76da756bdd1bf489dab6b0110a6a69aa5a9c58f0bb219e51888d08f3a0cb37

test:
  secret_key_base: 05264618a3ac6889a4641cc6c77a8449c9364696eb5db294f822f235e36949e6e3191f7de8bd31b25fc8f3075580a6093a61ae9d940e10b4c97713f16534b0bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
